# config/logging.yaml
version: 1
formatters:
  detailed:
    format: '%(asctime)s %(name)s %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/api.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
loggers:
  uvicorn.error:
    level: INFO
    handlers: [console, file]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: no

  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  api:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  src:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: WARNING
  handlers: [console, file]